name: Nightly Tests

on:
  schedule:
    # Will run at 00:00 every day
    - cron: "0 0 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Install plugin
        run: make install-plugin
      - name: Build binaries
        run: make build
      - name: Run e2e test
        run: go tool gotestsum --format github-actions -- -count 1 -v ./builder/scaleway/builder_acc_test.go -timeout=120m
        env:
          PACKER_ACC: 1
          PACKER_LOG: 1
          SCW_DEBUG: 1
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
      - name: Fetch log file
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: packer-log
          path: ./builder/scaleway/packer_log_test-scaleway-builder-basic.txt
          if-no-files-found: error
          retention-days: 2
